FROM node:10.8.0

WORKDIR /home/dev/

# copy files.
COPY src/ ./src
COPY tsconfig.json ./
COPY package.json ./

# build package.
RUN npm install
RUN npm run build

EXPOSE 8080

# run service.
CMD npm start